#!/bin/bash
set -eux 
HOME=$PWD
KIBANA_SOURCE=$(config-get kibana_source)
KIBANA_SOURCE_UNPACK_DIRECTORY=$(config-get kibana_source_unpack_directory)
KIBANA_SOURCE_CHECKSUM=$(config-get kibana_source_checksum)
HOST=$(unit-get private-address)

juju-log "install dependency"
apt-get install -y curl wget git nginx

juju-log "download kibana from elasticsearch.org"
wget -q -O /tmp/kibana.tgz ${KIBANA_SOURCE}
echo "${KIBANA_SOURCE_CHECKSUM}  /tmp/kibana.tgz" > /tmp/kibana.tgz.md5
md5sum -c /tmp/kibana.tgz.md5

install -o root -g root -m 0644 files/charm/nginx.conf /etc/nginx/sites-available/kibana
install -o root -g root -m 0644 files/charm/nginx_lb.conf /etc/nginx/sites-available/es_cluster

pushd /srv

tar xzvf /tmp/kibana.tgz
mv ${KIBANA_SOURCE_UNPACK_DIRECTORY} kibana3

rm -f /etc/nginx/sites-enabled/default

popd

rm -f /srv/kibana3/config.js
install -o root -g root -m 0644 files/charm/config.js /srv/kibana3/config.js


ln -s /etc/nginx/sites-available/kibana /etc/nginx/sites-enabled/kibana
ln -s /etc/nginx/sites-available/es_cluster /etc/nginx/sites-enabled/es_cluster

service nginx restart
