#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
set -eux # -x for verbose logging to juju debug-log

juju-log $JUJU_REMOTE_UNIT modified its settings

juju-log "##############################################################"
juju-log "#        Relationship Advice -     $JUJU_REMOTE_UNIT         #"
juju-log "##############################################################"
juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

CLUSTER_NAME=`relation-get cluster-name`
ES_HOST=`relation-get host`

juju-log "joining elasticsearch cluster ${CLUSTER_NAME} - host ${ES_HOST}"
# host setting should ensure this works even when multicast discovery is broken

sed -i "s|Elasticsearch =.*|Elasticsearch = \"${ES_HOST}:9200\"|" /opt/kibana/KibanaConfig.rb
initctl restart kibana