#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
set -eux # -x for verbose logging to juju debug-log
[ -z "$(relation-get cluster-name)" ] && exit 0

juju-log $JUJU_REMOTE_UNIT modified its settings

juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

echo "upstream es_cluster {"   > /etc/nginx/sites-available/es_cluster

CLUSTER_NAME=`relation-get cluster-name`
ES_HOST_LIST="none"
for MEMBER in `relation-list`
do
  ES_HOST=`relation-get private-address ${MEMBER}`
  echo "  server ${ES_HOST}:9200;" >> /etc/nginx/sites-available/es_cluster
done

echo "}" >> /etc/nginx/sites-available/es_cluster

juju-log "modified list of ES hosts kibana can talk to :-"
cat /etc/nginx/sites-available/es_cluster

service nginx restart
