#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed, modified, or broken
# This script should be idempotent.
set -eux # -x for verbose logging to juju debug-log

juju-log $JUJU_REMOTE_UNIT modified its settings

juju-log Relation settings:
relation-get
juju-log Relation members:
relation-list

CLUSTER_NAME=`relation-get cluster_name`
ES_HOST_LIST="none"
for MEMBER in `relation-list`
do
  ES_HOST=`relation-get private-address ${MEMBER}`
  if [  ${ES_HOST_LIST} = "none" ]; then
    ES_HOST_LIST="'${ES_HOST}:9200'"
  else
    ES_HOST_LIST=${ES_HOST_LIST},"'${ES_HOST}:9200'"
  fi
done

juju-log "joined elasticsearch : ${CLUSTER_NAME} - hosts ${ES_HOST_LIST}"
# host setting should ensure this works even when multicast discovery is broken

sed -i "s|Elasticsearch =.*|Elasticsearch = [ ${ES_HOST_LIST} ]|" /opt/kibana/KibanaConfig.rb
initctl restart kibana
service rinetd restart