#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'

initctl start kibana
#open-port 5601/tcp
sleep 10s
service rinetd start
open-port 80/tcp
