#!/bin/bash
# This must be renamed to the name of the relation. The goal here is to
# affect any change needed by relationships being formed
# This script should be idempotent.
set -eux # -x for verbose logging to juju debug-log
juju-log $JUJU_REMOTE_UNIT joined

# Set ip/port for web relation
relation-set port="80"
relation-set host=`unit-get private-address`